### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by cpsc-helper** [breeeak/AF_location#2]
Traceback (most recent call last):
  File "entry_2021.py", line 145, in <module>
    get_json(TESTSET_PATH,RESULT_PATH)
  File "entry_2021.py", line 37, in get_json
    checkpoint = torch.load(model_path)
  File "/export/anaconda3/envs/breeeak/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/export/anaconda3/envs/breeeak/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/export/anaconda3/envs/breeeak/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/model_best.pth.tar'

**Comment by breeeak** [comment]
Now I update the instruction for running the script.  You can run it as follow. Any questions please do not hesitate to ask me. Thank you.
----
Generate JSON File for the Entry of CSPC2001

1. Install all requirements in requirements.txt
2. Download the trained model[af_model_best.pth.tar](https://portland-my.sharepoint.com/:u:/g/personal/shuomeng2-c_my_cityu_edu_hk/EWLV-8ljcohJh6UT8_s_S8UBkEQsw4_1Bfcm1VbDxklWxw?e=2JyVbd) 
and put it in the `./checkpoint/af_model_best.pth.tar`checkpoint directory
3. `python entry_2021.py <test_path> <test_result_path> <trained_model_path>`
4. for example: 
    - python entry_2021.py "./test_path" "./test_result_path" "./checkpoint/af_model_best.pth.tar"`
